version: '3'
services:
    expub_enterprise_prod:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=production
        restart: always
        ports:
            - '3001:3001'
