version: '3'
services:
    knowledgecafe:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=production
        restart: always
        ports:
            - '3001:3001'
